# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
commands:
  build-setup:
    steps:
      - checkout

executors:
  docker-executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build:
    executor: docker-executor
    steps:
      - build-setup
      - run: npm i
      - run: npm run lint

  test:
    executor: docker-executor
    steps:
      - build-setup
      - run: npm i
      - run: npm run test
        
  analyze:
    executor: docker-executor
    steps:
      - build-setup
      - run: npm audit

workflows:
  # Name the workflow "welcome"
  default:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
